@ECHO OFF

ECHO Dear %username%,
ECHO ----------------
ECHO If you're reading this, that most likely means
ECHO you've angered me in some way shape or form.
ECHO Whether that've been present, future, or past.
ECHO The file YOU'VE chosen to download is my very own,
ECHO Custom-Made computer virus! Congrats! You are the
ECHO very first person to try out this new virus! 

ECHO.

ECHO Now, before you start freaking out, I would like to 
ECHO point out that this virus is COMPLETELY HARMLESS. Although
ECHO at times it can be annoying, it will NEVER voluntarily
ECHO do anything to harm your device. To delete said virus
ECHO from your device, you must open the newly generated
ECHO "PASSWORD_PROTECTION.EXE" file placed on your Desktop.

ECHO.

ECHO This will open software with the feild "Enter Password: ".
ECHO If you're wondering what the password is, you can be given
ECHO hints via the HINTS folder. (On your Desktop)
ECHO Try to think outside of the box for this! I'm really hoping
ECHO to challenge your thought, I want to see how long it takes
ECHO before you crack the code.
ECHO Before you begin the triumph of your Journey, just remember:

ECHO .

ECHO The password is really challenging to find! It's a super secret one!

PAUSE